package com.epam.kgd.victory.dao;

import com.epam.kgd.victory.bean.Good;
import com.epam.kgd.victory.dao.exception.DAOException;

/**
 * DAO interface for work (mainly) with Good type entities
 */
public interface GoodDAO extends BaseDAO<Good> {

	/**
	 * Add good in storage. More specific method, because return id after adding in storage
	 * 
	 * @param good - entity for adding
	 * @return autogenerated id after adding in storage
	 * @throws DAOException
	 */
	int addGood(Good good) throws DAOException;
}